export const shopCategories = [
  { value: 'mobile', label: 'Mobile Phones & Accessories' },
  { value: 'laptop', label: 'Laptops & Computer Accessories' },
  { value: 'fashion', label: 'Clothing & Fashion Accessories' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'home', label: 'Home Appliances & Furniture' },
  { value: 'grocery', label: 'Groceries & Daily Essentials' },
  { value: 'electronics', label: 'Consumer Electronics' },
  { value: 'toys', label: 'Toys, Kids & Baby Products' },
  { value: 'sports', label: 'Sports & Outdoor Equipment' },
  { value: 'automotive', label: 'Automotive & Motorbike Accessories' },
  { value: 'book', label: 'Books & Stationery' },
  { value: 'pet', label: 'Pet Supplies' },
  { value: 'jewelry', label: 'Jewelry & Watches' },
  { value: 'gaming', label: 'Gaming & Gaming Gear' },
  { value: 'health', label: 'Health & Medical Supplies' },
  { value: 'furniture', label: 'Furniture & Home Decor' },
  { value: 'camera', label: 'Cameras & Photography Equipment' },
  { value: 'babycare', label: 'Baby Care & Essentials' },
  { value: 'shoes', label: 'Shoes & Footwear' },
  { value: 'bags', label: 'Bags, Luggage & Travel Accessories' },
  { value: 'office', label: 'Office Supplies & Equipment' },
  { value: 'musical', label: 'Musical Instruments & Accessories' },
  { value: 'kitchen', label: 'Kitchenware & Dining' },
  { value: 'garden', label: 'Gardening & Outdoor Living' },
  { value: 'tool', label: 'Tools & DIY Equipment' },
  { value: 'green', label: 'Eco-friendly & Sustainable Products' },
  { value: 'hobby', label: 'Hobbies & Collectibles' },
  { value: 'alcohol', label: 'Wine, Beer & Spirits' },
  { value: 'smart', label: 'Smart Home Devices' },
  { value: 'digital', label: 'Digital Goods & Subscriptions' },
  { value: 'supplement', label: 'Vitamins & Supplements' },
  { value: 'stationery', label: 'Stationery & Art Supplies' },
  { value: 'lighting', label: 'Lighting & Fixtures' },
  { value: 'travel', label: 'Travel Essentials & Accessories' },
  { value: 'cleaning', label: 'Cleaning Supplies & Tools' },
  { value: 'storage', label: 'Storage & Organization' },
  { value: 'outdoor', label: 'Camping & Outdoor Gear' },
  { value: 'watch', label: 'Watches & Smartwatches' },
  { value: 'lingerie', label: 'Lingerie & Sleepwear' },
  { value: 'party', label: 'Party Supplies & Decorations' },
  { value: 'craft', label: 'Craft Supplies & Handmade Goods' },
  { value: 'hardware', label: 'Hardware & Industrial Equipment' },
  { value: 'security', label: 'Home Security & Surveillance' },
  { value: 'lightingdecor', label: 'Home Lighting & Decor' },
  { value: 'baking', label: 'Baking & Pastry Supplies' },
  { value: 'accessory', label: 'Phone & Tech Accessories' },
  { value: 'luxury', label: 'Luxury Goods & Designer Brands' },
  { value: 'event', label: 'Event & Wedding Supplies' },
  { value: 'gift', label: 'Gifts & Special Occasion Items' },
  { value: 'subscription', label: 'Subscription Boxes & Services' },
  { value: 'orther', label: 'Orther' },
];
